export const countryCoords: Record<string, [number, number]> = {
  Poland: [52, 19],
  Germany: [51, 10],
  USA: [38, -97],
  "United Kingdom": [55, -3],
  France: [46, 2],
  Japan: [36, 138],
  Russia: [61, 105],
  China: [35, 105],
  India: [20, 77],
  Canada: [56, -106],
  Australia: [-25, 133],
  Netherlands: [52, 5],
  Switzerland: [46, 8],
  Sweden: [60, 18],
  Italy: [41, 12],
  Spain: [40, -3],
  Belgium: [50, 4],
  Austria: [47, 13],
  Denmark: [56, 10],
  Norway: [60, 8],
  Finland: [64, 26],
  Ireland: [53, -8],
  Israel: [31, 34],
  "South Africa": [-30, 25],
  Argentina: [-63, -57],
  Brazil: [-14, -51],
  Mexico: [23, -102],
  Hungary: [47, 19],
  Portugal: [39, -8],
  Greece: [39, 21],
  Turkey: [38, 35],
  Egypt: [26, 30],
  Pakistan: [30, 69],
  Iran: [32, 53],
  "South Korea": [35, 127],
  Taiwan: [23, 121],
  Ukraine: [48, 31],
  Romania: [45, 24],
  "New Zealand": [-40, 174],
  Cuba: [21, -77],
  Chile: [-35, -71],
  Colombia: [4, -72],
  Peru: [-9, -75],
  Indonesia: [-0.5, 113],
  Vietnam: [14, 108],
  Thailand: [15, 100],
  Serbia: [44, 21],
  Croatia: [45, 15],
  Slovenia: [46, 15],
  Slovakia: [48, 19],
  Iceland: [64, -19],
  Luxembourg: [49, 6],
  Lithuania: [55, 24],
  "Czech Republic": [50, 15],
  Czechia: [50, 15],
  Singapore: [1, 104],
  "Hong Kong": [22, 114],
  "Saudi Arabia": [24, 45],
  "United Arab Emirates": [24, 54],
}

export const countryCodeMap: Record<string, string> = {
  Poland: "pl",
  Germany: "de",
  USA: "us",
  "United Kingdom": "gb",
  France: "fr",
  Japan: "jp",
  Russia: "ru",
  China: "cn",
  India: "in",
  Canada: "ca",
  Australia: "au",
  Netherlands: "nl",
  Switzerland: "ch",
  Sweden: "se",
  Italy: "it",
  Spain: "es",
  Belgium: "be",
  Austria: "at",
  Denmark: "dk",
  Norway: "no",
  Finland: "fi",
  Ireland: "ie",
  Israel: "il",
  "South Africa": "za",
  Argentina: "ar",
  Brazil: "br",
  Mexico: "mx",
  Hungary: "hu",
  Portugal: "pt",
  Greece: "gr",
  Turkey: "tr",
  Egypt: "eg",
  Pakistan: "pk",
  Iran: "ir",
  "South Korea": "kr",
  Taiwan: "tw",
  Ukraine: "ua",
  Romania: "ro",
  "New Zealand": "nz",
  Cuba: "cu",
  Chile: "cl",
  Colombia: "co",
  Peru: "pe",
  Indonesia: "id",
  Vietnam: "vn",
  Thailand: "th",
  Serbia: "rs",
  Croatia: "hr",
  Slovenia: "si",
  Slovakia: "sk",
  Iceland: "is",
  Luxembourg: "lu",
  Lithuania: "lt",
  "Czech Republic": "cz",
  Czechia: "cz",
  Singapore: "sg",
  "Hong Kong": "hk",
  "Saudi Arabia": "sa",
  "United Arab Emirates": "ae",
}

export function getCountryCoordinates(name: string): [number, number] | undefined {
  return countryCoords[name]
}

export function getCountryCode(name: string): string | undefined {
  return countryCodeMap[name]
}